use ../core.nu *
use ../probe-cache.nu

# ./configure && make [check] && make install, also plain-Makefile projects.
# CONFIG_SHELL: bash when a build dependency, else the seed's dash (base userland only)
export def --env setup []: nothing -> nothing {
  let sh = (if (which bash | is-not-empty) { tool bash } else { tool sh })
  load-env {CONFIG_SHELL: $sh, SHELL: $sh}
}

export def workdir []: nothing -> string { if (options autotools).outOfTree { (ctx).build } else { project-dir autotools } }

# gnulib's gettext.h without NLS: `((void) d, gettext (s))`. clang no longer sees a string
# literal behind the comma operator and -Werror=format-security rejects every _("...")
def gnulib-gettext-literal [src: string]: nothing -> nothing {
  const FALLBACK = "((void) (Domainname), gettext (Msgid))"
  for f in (glob $"($src)/**/gettext.h" | where { open --raw $in | str contains $FALLBACK }) {
    edit $f { str replace -a $FALLBACK "gettext (Msgid)" | str replace -a "((void) (Category), dgettext (Domainname, Msgid))" "dgettext (Domainname, Msgid)" }
  }
}

# configure's INSTALL: the seed's path would be a store reference in rbconfig.rb and python's
# sysconfig, a bare name gets ../ prepended per subdirectory. So a copy in the build dir, and
# after `make install` the files that recorded it say plain `install` (found on PATH)
def install-tool []: nothing -> string { $"((ctx).build)/install" }

def unrecord-install-tool [out: string]: nothing -> nothing {
  # grep, not glob+open: one process over the tree instead of nu reading every file
  let files = (^grep -rlFI (install-tool) $out | complete | get stdout | lines)
  for f in $files { edit $f { str replace -a (install-tool) install } }
}

# ./configure --prefix=$out --enable-shared, --host/--build when cross, `autotools.flags` last.
# Real autoconf scripts also get: cached probe results, no message catalogues, no .deps files
export def --env configure []: nothing -> nothing {
  let c = (ctx); let o = (options autotools)
  let script = $"($c.src)/($o.configureScript)"
  if not ($script | path exists) {
    error make {msg: $"configure script not found: ($script)"}
  }

  # --host: configure stops running test programs. --build only has to differ from it
  let host_flags = (if $c.platform.cross { [$"--host=($c.platform.configTriple)" "--build=x86_64-build-linux-gnu"] } else { [] })
  let is_autoconf = (open --raw $script | str substring 0..2000 | $in =~ "Generated by GNU Autoconf")
  let autoconf = (if $is_autoconf {
    let cache = $"($c.build)/config.cache"
    let key = (probe-cache key autoconf [$script])
    let restored = (probe-cache restore $key $cache)
    note config.cache (if $restored { "restored" } else { "cold" })
    gnulib-gettext-literal $c.src
    cp (tool install) (install-tool)
    {
      key: $key
      cache: $cache
      restored: $restored
      flags: [
        $"--cache-file=($cache)"
        --disable-nls
        --disable-dependency-tracking
        --disable-static
        --enable-shared
        $"INSTALL=(install-tool) -c"
      ]
    }
  } else { null })
  let autoconf_flags = ($autoconf.flags? | default [])
  x $env.CONFIG_SHELL $script $"--prefix=($c.out)" ...$autoconf_flags ...$host_flags ...$o.flags
  if $autoconf != null and not $autoconf.restored { probe-cache store $autoconf.key $autoconf.cache }
}

# make -j (`autotools.buildTarget`, `autotools.makeFlags`)
export def build []: nothing -> nothing {
  let c = (ctx); let o = (options autotools)
  x make $"-j($c.njobs)" ...$o.buildTarget ...($o.makeFlags)
}

# make check (or `autotools.testTarget`), tests.parallel as -j
export def test []: nothing -> nothing {
  let o = (options autotools)
  x make $"-j(test-jobs)" ...$o.testTarget ...($o.makeFlags)
}

# make install (`autotools.installTarget`, `autotools.makeFlags`)
export def install []: nothing -> nothing {
  let c = (ctx); let o = (options autotools)
  # PREFIX/prefix: for hand-written Makefiles, configure'd ones ignore them
  x make install $"PREFIX=($c.out)" $"prefix=($c.out)" ...($o.makeFlags) ...$o.installFlags
  unrecord-install-tool $c.out
}
